(()=>{'use strict';
let csrf='',me=null,current='communications',commPoll=null;
const API_BASE=((window.METHOD_OS_CONFIG&&window.METHOD_OS_CONFIG.apiBase)||'').replace(/\/$/,'');
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(csrf&&opt.method&&opt.method!=='GET')opt.headers['X-CSRF-Token']=csrf;const r=await fetch(API_BASE+url,Object.assign({credentials:'include'},opt));let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||('HTTP '+r.status));return j}
const nav=[['communications','✦','Диалоги'],['system','⚙','Система']];
function setTitle(k,t){$('#kicker').textContent=k;$('#title').textContent=t}
function tag(s){let c=/ready|active|open|ok/i.test(s)?'good':/error|blocked|stopped|no/i.test(s)?'bad':'warn';return `<span class="tag ${c}">${esc(s||'—')}</span>`}
function niceDate(s){if(!s)return'—';try{return new Date(s).toLocaleString('ru-RU',{dateStyle:'short',timeStyle:'short'})}catch{return esc(s)}}
function attrLine(a){if(!a)return'атрибуция: —';const bits=[];if(a.clientId)bits.push('cid '+a.clientId);if(a.yclid)bits.push('yclid '+a.yclid);if(a.utm_source)bits.push(a.utm_source);if(a.utm_campaign)bits.push(a.utm_campaign);return bits.length?bits.join(' · '):'атрибуция: —'}
async function boot(){try{const x=await api('/api/me');me=x.user;csrf=x.csrf;$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#userMini').className='user-mini';$('#userMini').innerHTML=`<b>${esc(me.name)}</b><span>${esc(me.role)} · ${esc(me.email)}</span>`;$('#nav').innerHTML=nav.map(n=>`<button class="nav-btn" data-route="${n[0]}"><span class="nav-icon">${n[1]}</span><span class="nav-label">${n[2]}</span></button>`).join('');$('#nav').onclick=e=>{const b=e.target.closest('[data-route]');if(b)route(b.dataset.route)};route(current)}catch{$('#login').classList.remove('hidden')}}
async function route(r){if(commPoll&&r!=='communications'){clearInterval(commPoll);commPoll=null}current=r;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===r));try{if(r==='communications')await communications();if(r==='system')await system()}catch(e){$('#view').innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
async function communications(selectedId){if(commPoll){clearInterval(commPoll);commPoll=null}setTitle('COMMUNICATIONS','Диалоги MAX');const [list,status]=await Promise.all([api('/api/communications'),api('/api/integrations/max/status')]);const items=list.items||[];const id=String(selectedId||new URLSearchParams(location.search).get('conversation')||(items[0]&&items[0].id)||'');const detail=id?await api('/api/communications/'+encodeURIComponent(id)):null;const cfg=status.configured?'<span class="tag good">MAX READY</span>':'<span class="tag warn">НУЖНА НАСТРОЙКА</span>';
const left=items.length?items.map(x=>`<button class="conv-item ${String(x.id)===id?'active':''}" data-conv="${esc(x.id)}"><span class="conv-main"><b>${esc(x.display_name||'MAX пользователь')}</b>${Number(x.unread_count||0)>0?`<i>${Number(x.unread_count)}</i>`:''}</span><small>${esc(x.last_message||'Диалог начат')}</small><time>${niceDate(x.last_message_at||x.updated_at||x.created_at)}</time></button>`).join(''):'<div class="empty">MAX ещё не прислал ни одного диалога.</div>';
let right='<div class="empty inbox-empty">Выберите диалог.</div>';
if(detail){const c=detail.conversation,msgs=detail.messages||[];right=`<div class="chat-head"><div><p class="eyebrow">MAX · ${esc(c.username?('@'+c.username):c.external_user_id||'')}</p><h2>${esc(c.display_name||'MAX пользователь')}</h2><small>${esc(attrLine(c.attribution))}${c.payload?` · start: <span class="mono">${esc(c.payload)}</span>`:''}</small></div><span>${tag(c.status||'open')}</span></div><div class="messages">${msgs.length?msgs.map(m=>`<div class="message ${m.direction==='out'?'out':m.direction==='system'?'system':'in'}"><div>${esc(m.body||'')}</div><small>${niceDate(m.created_at)}${m.edited_at?' · изменено':''}${m.removed_at?' · удалено':''}</small></div>`).join(''):'<div class="empty">Сообщений пока нет.</div>'}</div><form id="sendMaxForm" class="composer"><textarea class="field" name="text" maxlength="4000" required placeholder="Написать в MAX..."></textarea><button class="btn primary" type="submit">ОТПРАВИТЬ</button></form>`}
$('#view').innerHTML=`<div class="section-head inbox-toolbar"><div>${cfg}<small class="inbox-config">owner: ${esc(status.owner||'—')} · storage: ${esc(status.storage||'—')}</small></div><button class="mini-btn" id="refreshInbox">Обновить</button></div><div class="inbox"><aside class="conv-list">${left}</aside><section class="chat-pane">${right}</section></div>`;
$('#view').onclick=e=>{const b=e.target.closest('[data-conv]');if(b)communications(b.dataset.conv);const r=e.target.closest('#refreshInbox');if(r)communications(id)};const f=$('#sendMaxForm');if(f)f.onsubmit=async e=>{e.preventDefault();const text=new FormData(e.target).get('text');const btn=e.target.querySelector('button');btn.disabled=true;try{await api('/api/communications/'+encodeURIComponent(id)+'/send',{method:'POST',body:JSON.stringify({text})});await communications(id)}catch(err){btn.disabled=false;alert('MAX: '+err.message)}};commPoll=setInterval(()=>{if(current==='communications'&&!document.querySelector('.composer textarea:focus'))communications(id).catch(()=>{})},5000)}
async function system(){setTitle('SYSTEM','Система');const mx=await api('/api/integrations/max/status');$('#view').innerHTML=`<div class="grid metrics"><div class="card metric"><strong>110906734</strong><span>Метрика</span></div><div class="card metric"><strong>${mx.configured?'READY':'SETUP'}</strong><span>MAX Inbox</span></div></div><div class="section card"><h2>Текущий production-контур</h2><div class="list"><div class="list-item"><b>Сайт + админка</b><small>marafon-metod.ru /admin/</small></div><div class="list-item"><b>Backend</b><small>api.marafon-metod.ru → metod-payment-test</small></div><div class="list-item"><b>MAX owner</b><small>${esc(mx.owner||'—')}</small></div><div class="list-item"><b>Хранилище диалогов</b><small>${esc(mx.storage||'—')}</small></div><div class="list-item"><b>Bridge</b><small>${mx.bridge?'готов':'нужна METHOD_OS_BRIDGE_SECRET'}</small></div></div></div>`}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;const r=await api('/api/login',{method:'POST',body:JSON.stringify({email,password})});csrf=r.csrf;await boot()}catch(err){$('#loginError').textContent='Не удалось войти: '+err.message}};
$('#logoutBtn').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:'{}'})}catch{}location.reload()};
boot();
})();
